language: php
php:
  - 7.0
  - 7.1
  - 7.2

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database test;' -U postgres
  - cp  .travis.parameters_test.pgsql.yml  app/config/parameters.yml
  - cp  .travis.parameters_test.pgsql.yml  app/config/parameters_test.yml
  - composer install --dev --no-interaction
  - wget https://phar.phpunit.de/phpunit-6.3.phar

script: php phpunit-6.3.phar  --configuration app/


