jmb_technology_user_accounts:
    resource: "@JMBTechnologyUserAccountsBundle/Resources/config/routing.yml"
    prefix:   /

directoki:
    resource: "@DirectokiBundle/Resources/config/routing.yml"
    prefix:   /


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
